name: Docker-build-publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: registry.hub.docker.com
  IMAGE_NAME: patanouk/linux-container

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set docker image tag
        id: docker-image-tag
        run: echo "DOCKER_TAG=patanouk/linux-playground-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: my-step
        run: echo ${{ steps.docker-image-tag.outputs.tags.DOCKER_TAG }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker-image-tag.outputs.tags.DOCKER_TAG }}
